### ISSUE TITLE
Presentation and Images

### ISSUE THREAD

**Issue by Nabeel-K** [CorporateMinions/your-next-trip#4]
Work on presentation as project is being worked on. Load and suggest more images.

**Comment by andresramirezz** [comment]
Hi Team.
I am attaching two images (Bus.png and Qline.png) with better resolution so that we can use them as background in the three sheets, in the following order:

- index.jsp (Qline.png)
- recommendation.jsp (Bus.png)
- about.jsp (Qline.png).

Regards,

![Bus](https://user-images.githubusercontent.com/44705838/70865033-bc80d700-1f26-11ea-932b-af40df4ca8af.png)
![Qline](https://user-images.githubusercontent.com/44705838/70865034-bc80d700-1f26-11ea-93ec-e392d43fe995.png)
